// src/components/Resizer.svelte
<script lang="ts">
  import { Platform } from 'obsidian'
  import { onMount } from 'svelte'
  import interact from 'interactjs'

  export let height: number

  let resizer: HTMLDivElement

  onMount(() => {
    interact(resizer).draggable({
      listeners: {
        move(e) {
          height += e.dy
        },
      },
    })
  })
</script>

<div
  bind:this={resizer}
  class="resizer"
  class:taller={Platform.isMobile || Platform.isMobileApp}
/>

<style>
  .resizer {
    transition: all;
    transition-duration: 200ms;
    height: 5px;
    background-color: var(--divider-color);
    border-radius: var(--radius-s);
    cursor: row-resize !important;
    touch-action: none;
  }

  .resizer.taller {
    height: 15px;
  }

  .resizer:hover {
    background-color: var(--interactive-accent);
  }
</style>

// src/react/resizer/Resizer.tsx
import { useContext } from 'react'
import { Platform } from 'obsidian'
import { Draggable } from 'gsap/Draggable'
import { StateManagerContext } from '../contexts/StateManagerContext'

export function Resizer() {
  const stateManager = useContext(StateManagerContext)

  function setupDraggable(div: HTMLDivElement): () => void {
    const draggable = new Draggable(div, {
      type: 'top',

      onDrag() {
        stateManager.update(state => {
          state.height += draggable.deltaY
        })
      },
    })

    return () => {
      draggable.kill()
    }
  }

  return (
    <>
      <div
        ref={setupDraggable}
        className={`resizer ${Platform.isMobile || Platform.isMobileApp ? 'taller' : ''}`}
      />
      <style>{`
      .resizer {
        transition: all;
        transition-duration: 200ms;
        height: 5px;
        background-color: var(--divider-color);
        border-radius: var(--radius-s);
        cursor: row-resize !important;
        touch-action: none;
      }
    
      .resizer.taller {
        height: 15px;
      }
    
      .resizer:hover {
        background-color: var(--interactive-accent);
      }
    `}</style>
    </>
  )
}
